//this is /Users/sahibabc/ecomLanding/ecomlanding/src/app/layout.tsx
// this file is the root layout for the Next.js application
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import Header from "../../components/layout/Header";
import { Toaster } from "sonner";
import DevAuthSwitch from "../../components/admin/DevAuthSwitch";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Header />
//         <Toaster position="top-right" richColors closeButton />
//         {children}
//         <DevAuthSwitch /> 
//       </body>
//     </html>
//   );
// }
export default function StoreLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <Toaster position="top-right" richColors closeButton />
      {children}
       <DevAuthSwitch />
    </>
  );
}